#include <syslog.h>
//这是一个测试程序,测试syslog守护进程，syslog函数的使用方法
//配置文件为/etc/rsyslog.conf; rsyslog.conf配置文件读取/etc/rsyslog.d/Jiakun_syslog.conf配置文件
//在Jiakun_syslog.conf中设置产生的日志文件位置和名字
int main(int argc, char const *argv[])
{
	openlog(argv[0],LOG_CONS|LOG_PID|LOG_PERROR,LOG_LOCAL2);
	syslog(LOG_DEBUG,"Hello,This ia a syslog test message generated by program '%s':%m\n",argv[0]);
	closelog();
	return 0;
}
